#!/usr/bin/env bash
# cron-client: Host-side Cronicle worker lifecycle management.
# Installs, monitors, and removes a Cronicle worker on the host machine.
# The worker connects to the central Cronicle server (Docker) and executes
# scheduled tasks locally using the host's full environment.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
SKILL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OPENDAWG_ROOT="${OPENDAWG_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
export PATH="${OPENDAWG_ROOT}/.opendawg/bin:${PATH}"

INSTALL_DIR="${CRONICLE_WORKER_DIR:-/opt/cronicle}"
ENV_FILE="${HOME}/.opendawg/cron-env"

usage() {
  cat <<'EOF'
Usage: cron-client <command> [options]

Commands:
  install [--server-url <url>] [--secret <key>]
                                Install and register Cronicle worker on this host
  status                        Show worker status and connection info
  uninstall [--purge]           Stop and remove the worker

The worker connects to the central Cronicle server and executes scheduled
tasks locally, with full access to the host environment (opencode, API keys,
session data).

Server config is auto-discovered from config-cli vault if available.
EOF
}

# --- Helpers ---

inject_from_vault() {
  if command -v config-cli &>/dev/null; then
    local val
    if [[ -z "${CRONICLE_URL:-}" ]]; then
      val="$(config-cli get CRONICLE_URL 2>/dev/null || true)"
      [[ -n "$val" ]] && CRONICLE_URL="$val"
    fi
    if [[ -z "${CRONICLE_SECRET:-}" ]]; then
      val="$(config-cli get CRONICLE_SECRET 2>/dev/null || true)"
      [[ -n "$val" ]] && CRONICLE_SECRET="$val"
    fi
    if [[ -z "${CRONICLE_API_KEY:-}" ]]; then
      val="$(config-cli get CRONICLE_API_KEY 2>/dev/null || true)"
      [[ -n "$val" ]] && CRONICLE_API_KEY="$val"
    fi
  fi
}

is_worker_running() {
  if command -v systemctl &>/dev/null && systemctl is-active cronicle &>/dev/null; then
    return 0
  elif [[ -f "${INSTALL_DIR}/logs/cronicled.pid" ]]; then
    local pid
    pid=$(cat "${INSTALL_DIR}/logs/cronicled.pid" 2>/dev/null || echo "")
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
  fi
  return 1
}

# --- Create environment profile ---
# This file is sourced by the worker's systemd service so jobs have access
# to the same environment as a user-invoked opendawg-agent.sh.
create_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")"

  cat > "$ENV_FILE" << ENVEOF
# Auto-generated by cron-client install — do not edit manually.
# Sourced by Cronicle worker systemd service for job execution environment.
# Format: plain KEY=value (no 'export' — compatible with systemd EnvironmentFile=)
PATH=${OPENDAWG_ROOT}/.opendawg/bin:${HOME}/.opencode/bin:${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin
OPENDAWG_ROOT=${OPENDAWG_ROOT}
HOME=${HOME}
ENVEOF

  # Inject current vault secrets into the env file
  if command -v config-cli &>/dev/null; then
    local vault_output
    vault_output="$(config-cli get-all 2>/dev/null || echo "")"
    if [[ -n "$vault_output" ]]; then
      echo "" >> "$ENV_FILE"
      echo "# Vault secrets (snapshot at install time — re-run 'cron-client install' to refresh)" >> "$ENV_FILE"
      # Strip 'export ' prefix for systemd EnvironmentFile= compatibility
      echo "$vault_output" | sed 's/^export //' >> "$ENV_FILE"
    fi
  fi

  chmod 600 "$ENV_FILE"
  echo "[cron-client] Environment file written to ${ENV_FILE}"
}

# --- Commands ---

cmd_install() {
  local server_url="${CRONICLE_URL:-}"
  local secret="${CRONICLE_SECRET:-}"

  # Parse flags
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --server-url) server_url="${2:?Error: --server-url requires URL}"; shift 2 ;;
      --secret)     secret="${2:?Error: --secret requires value}"; shift 2 ;;
      *) echo "Error: Unknown option '$1'" >&2; return 1 ;;
    esac
  done

  # Try vault if not provided
  inject_from_vault
  server_url="${server_url:-${CRONICLE_URL:-}}"
  secret="${secret:-${CRONICLE_SECRET:-}}"

  if [[ -z "$server_url" ]]; then
    echo "Error: Server URL required. Provide --server-url or set CRONICLE_URL in vault." >&2
    return 1
  fi
  if [[ -z "$secret" ]]; then
    echo "Error: Server secret required. Provide --secret or set CRONICLE_SECRET in vault." >&2
    return 1
  fi

  # Check if already running
  if is_worker_running; then
    echo "[cron-client] Worker is already running on this host. Skipping installation."
    echo "[cron-client] Use 'cron-client uninstall' first to reinstall."
    return 0
  fi

  # Check Node.js prerequisite
  if ! command -v node &>/dev/null; then
    echo "Error: Node.js is required for Cronicle worker. Install Node.js 18+ first." >&2
    return 1
  fi

  echo "[cron-client] Installing Cronicle worker on $(hostname)..."
  echo "[cron-client] Server: ${server_url}"

  # Create environment file for job execution
  create_env_file

  # Delegate to install-worker.sh
  local installer="${SCRIPT_DIR}/install-worker.sh"
  if [[ ! -f "$installer" ]]; then
    echo "Error: install-worker.sh not found at ${installer}" >&2
    return 1
  fi

  # Patch systemd service to source our env file
  # We run install-worker.sh, then patch the service file
  sudo bash "$installer" \
    --server "$server_url" \
    --secret "$secret" \
    --install-dir "$INSTALL_DIR"

  # Patch systemd service to source environment
  if command -v systemctl &>/dev/null && [[ -f /etc/systemd/system/cronicle.service ]]; then
    if ! grep -q "EnvironmentFile" /etc/systemd/system/cronicle.service 2>/dev/null; then
      sudo sed -i "/\[Service\]/a EnvironmentFile=${ENV_FILE}" /etc/systemd/system/cronicle.service
      sudo systemctl daemon-reload
      sudo systemctl restart cronicle
      echo "[cron-client] Patched systemd service to source ${ENV_FILE}"
    fi
  fi

  echo ""
  echo "[cron-client] Worker installed and connected to ${server_url}"
  echo "[cron-client] Hostname: $(hostname)"
  echo "[cron-client] Env file: ${ENV_FILE}"
}

cmd_status() {
  inject_from_vault

  echo "=== Cron Client (Worker) ==="
  echo "  Hostname: $(hostname)"
  echo "  Install dir: ${INSTALL_DIR}"
  echo "  Env file: ${ENV_FILE}"

  if is_worker_running; then
    echo "  Status: RUNNING"
  else
    echo "  Status: STOPPED"
  fi

  if [[ -f "${INSTALL_DIR}/conf/config.json" ]]; then
    local server_url
    server_url=$(node -e "console.log(JSON.parse(require('fs').readFileSync('${INSTALL_DIR}/conf/config.json','utf8')).base_app_url)" 2>/dev/null || echo "unknown")
    echo "  Server: ${server_url}"
  else
    echo "  Server: (not configured)"
  fi

  # Check if server is reachable
  local server="${CRONICLE_URL:-http://localhost:3012}"
  if [[ -n "${CRONICLE_API_KEY:-}" ]]; then
    if curl -sf "${server}/api/app/get_schedule/v1?limit=0" \
       -H "X-API-Key: ${CRONICLE_API_KEY}" &>/dev/null; then
      echo "  Server reachable: YES"
    else
      echo "  Server reachable: NO"
    fi
  fi
}

cmd_uninstall() {
  local purge=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --purge) purge=true; shift ;;
      *) shift ;;
    esac
  done

  echo "[cron-client] Uninstalling worker from $(hostname)..."

  local installer="${SCRIPT_DIR}/install-worker.sh"
  if [[ -f "$installer" ]]; then
    local -a args=(--uninstall --install-dir "$INSTALL_DIR" --server dummy --secret dummy)
    [[ "$purge" == true ]] && args+=(--purge)
    sudo bash "$installer" "${args[@]}" 2>/dev/null || true
  else
    # Manual cleanup if install-worker.sh is missing
    if command -v systemctl &>/dev/null; then
      sudo systemctl stop cronicle 2>/dev/null || true
      sudo systemctl disable cronicle 2>/dev/null || true
      sudo rm -f /etc/systemd/system/cronicle.service
      sudo systemctl daemon-reload 2>/dev/null || true
    fi
  fi

  # Remove env file
  rm -f "$ENV_FILE"

  echo "[cron-client] Worker uninstalled."
}

# --- Dispatch ---
case "${1:-help}" in
  install)   shift; cmd_install "$@" ;;
  status)    shift; cmd_status "$@" ;;
  uninstall) shift; cmd_uninstall "$@" ;;
  help|--help|-h) usage ;;
  *)
    echo "Error: Unknown command '${1}'" >&2
    usage >&2
    exit 1
    ;;
esac
